### ISSUE TITLE
Compile project with dependent lib

### ISSUE THREAD

**Issue by mattiascibien** [noliar/dotnet-buildpack#4]
Hello,

I actualy use this nice buildpack to deploy my website from my ci server to my heroku app.

The problem is that when I specify the project using the `.deployment` file I get an error about a
dependent lib (which resides alongside my project and is correctly referenced in the project.json) I get an error about the lib not having a lock file.

Is there any way I can solve this?

Thank you and keep up the good work.

**Comment by buldo** [comment]
Could you provide some more information? Full error message?

**Comment by mattiascibien** [comment]
@buldo here is a pastebin http://pastebin.com/8wx15U0d.

**Comment by buldo** [comment]
@mattiascibien  I solved the same issue. But I forgot how.
I use travis to build and deploy. As I remember I added 

> skip_cleanup: true

into deploy config

```
deploy:
  provider: heroku
  skip_cleanup: true
```

**Comment by mattiascibien** [comment]
@buldo I use semaphore to build and deploy which is supposed to have automatic deploy to heroku.

EDIT: I will try to look for a similar setting in semaphore.

**Comment by noliar** [comment]
@mattiascibien 
um, I think that it's a bug of `dotnet restore`. If I reference a local project, it doesn't restore that project automatically. (You can see it in gif below.)
![bug](https://cloud.githubusercontent.com/assets/5773982/16973142/8841ee30-4e63-11e6-8b1d-0ffb079d6668.gif)

**Comment by mattiascibien** [comment]
@noliar damn... I guess I will have to use it as a custom nuget package then. I thought it was a bug too.

Thank you :+1:

**Comment by noliar** [comment]
I gave an issue and the answer is the behavior is by design. So I'll run  `dotnet restore`  at the root path for now.

**Comment by mattiascibien** [comment]
Thanks. :)
