### ISSUE TITLE
Failed to bind to $PORT

### ISSUE THREAD

**Issue by lonekorean** [noliar/dotnet-buildpack#5]
Hello. First of all, thanks for making this buildpack.

I'm trying to get a simple web API running. Deployment seems to go smoothly, but then I get this error:

> Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

I'm running VS 2015 update 3 + .NET Core 1.0 preview 2. The repo I'm working on is here: https://github.com/lonekorean/dot-net-heroku-test . The URL I'm trying to hit is here: http://dot-net-heroku-test.herokuapp.com/api/values .

More logs:

> 2016-07-20T00:23:15.649038+00:00 app[web.1]: Hosting environment: Production
> 2016-07-20T00:23:15.649314+00:00 app[web.1]: Now listening on: http://localhost:5000
> 2016-07-20T00:23:15.649317+00:00 app[web.1]: Application started. Press Ctrl+C to shut down.
> 2016-07-20T00:23:15.649051+00:00 app[web.1]: Content root path: /app/heroku_output
> 2016-07-20T00:24:13.045397+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
> 2016-07-20T00:24:13.045397+00:00 heroku[web.1]: Stopping process with SIGKILL
> 2016-07-20T00:24:13.991800+00:00 heroku[web.1]: Process exited with status 137
> 2016-07-20T00:24:14.006432+00:00 heroku[web.1]: State changed from starting to crashed
> 2016-07-20T00:24:16.016068+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/api/values" host=dot-net-heroku-test.herokuapp.com request_id=51558762-db25-46d4-8696-ab679f26f8b1 fwd="45.25.168.210" dyno= connect= service= status=503 bytes=
> 2016-07-20T00:24:16.442572+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/api/values" host=dot-net-heroku-test.herokuapp.com request_id=7845d9e2-efa2-46a0-8921-47155c3cab77 fwd="45.25.168.210" dyno= connect= service= status=503 bytes=
> 2016-07-20T00:24:16.703224+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=dot-net-heroku-test.herokuapp.com request_id=3c6a112a-e262-4a99-8c6a-0952df3b9bfc fwd="45.25.168.210" dyno= connect= service= status=503 bytes=

Any help is much appreciated.

**Comment by noliar** [comment]
Because it depends on some command args, You should read args in your main entry.
It means that you should add some code like this:
![image](https://cloud.githubusercontent.com/assets/5773982/16972457/37a36788-4e5e-11e6-877a-04cd0cec45be.png)

**Comment by lonekorean** [comment]
It works! Thank you so much!
