### ISSUE TITLE
How to set up the app to bind at the right port?

### ISSUE THREAD

**Issue by TomasHubelbauer** [noliar/dotnet-buildpack#7]
Hey, I've just picked up .NET Core, I was only observing it until now and have decided it is time to try it out. I'd like to use this Heroku buildpack (because it doesn't use Mono), but I am not sure how to deploy the app. I have created a clean _ASP .NET Core_ application (targetting .NET Core of course) and without change pushed it to heroku using `heroku create … && git push heroku master`.

I know I have to switch to self host instead of IIS and somehow configure the server start script to pick up the environment variable Heroku provides with the port, but I am not sure how to do it. Can you help, please?

EDIT: I see you have blogged about using this buildpack: http://notes.devzh.ml/2015/09/02/heroku-aspnet-5-buildpack/ I will try to use automated translation to follow the article, but it is one year old and mentions `dnu` when today `dotnet` should be used if I am not mistaked. Is there a more up to date resource? Can you include a short tutorial in ReadMe that would say how to build an example app with deployment configured and say PostgreSQL (because that's what Heroku provides I think) used for EF Core?

**Comment by noliar** [comment]
If you want to set the right PORT, you should add `Microsoft.Extensions.Configuration.CommandLine` dependency and write some code(metioned at issue https://github.com/noliar/dotnet-buildpack/issues/5#issuecomment-233816503)

**Comment by TomasHubelbauer** [comment]
I am sorry, but I still couldn't get it to work. I changed the `main` method to:

``` cs
        public static void Main(string[] args)
        {
            var config = new ConfigurationBuilder().AddCommandLine(args).Build();
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseConfiguration(config)
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
```

It compiles and builds fine and works locally, but I get the binding error all the same. _Web process failed to bind to $PORT within 60 seconds of launch_

How can I make sure the command line arguments contain the port? Does this buildpack pass them?

**Comment by TomasHubelbauer** [comment]
Nevermind, found https://github.com/noliar/ASP.NET-Core-Sample which works very well. I was able to deploy it, register, log out and log in. It provides working base upon which I can build. Thanks for putting all this work out.
