### ISSUE TITLE
Buildpack fails on heroku

### ISSUE THREAD

**Issue by flabbert** [noliar/dotnet-buildpack#8]
After working for a while, the buildpack now fails on heroku.

112 package(s) to /tmp/btrq5c3y.na5/btrq5c3y.na5.csproj
remote: MSBUILD : error MSB1009: Project file does not exist.
remote: Switch: /tmp/tmp.oQS4JivqzZ
remote:  !     Push rejected, failed to compile ASP.NET Core app.

**Comment by flabbert** [comment]
After checking some more, it seems like there is some bug in the sdk that the buildpack has started to download. As Microsoft.NET.Sdk 1.0.0-alpha-20161026-2. is part of the succeeding build, while the build fails with  Microsoft.NET.Sdk 1.0.0-alpha-20161029-1.

**Comment by flabbert** [comment]
-----> ASP.NET Core app detected
Installing Node
Installing bower
/tmp/tmp.ArkjaoI6r4/node-v4.4.4-linux-x64/bin/bower -> /tmp/tmp.ArkjaoI6r4/node-v4.4.4-linux-x64/lib/node_modules/bower/bin/bower
bower@1.7.9 /tmp/tmp.ArkjaoI6r4/node-v4.4.4-linux-x64/lib/node_modules/bower
Get .NET Core Version and Channel from the PROJECT
Get version from global.json
Installing the dependencies
Install package
-----> Cleaning apt caches
-----> Updating apt caches
       Ign http://archive.ubuntu.com trusty InRelease
       Get:1 http://apt.postgresql.org trusty-pgdg InRelease [46.7 kB]
       Get:2 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
       Get:3 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
       Hit http://archive.ubuntu.com trusty Release.gpg
       Hit http://archive.ubuntu.com trusty Release
       Get:4 http://apt.postgresql.org trusty-pgdg/main amd64 Packages [66.9 kB]
       Get:5 http://archive.ubuntu.com trusty-security/main amd64 Packages [542 kB]
       Ign http://apt.postgresql.org trusty-pgdg/main Translation-en_US
       Ign http://apt.postgresql.org trusty-pgdg/main Translation-en
       Get:6 http://archive.ubuntu.com trusty-security/main Translation-en [298 kB]
       Get:7 http://archive.ubuntu.com trusty-updates/main amd64 Packages [913 kB]
       Get:8 http://archive.ubuntu.com trusty-updates/main Translation-en [443 kB]
       Hit http://archive.ubuntu.com trusty/main amd64 Packages
       Hit http://archive.ubuntu.com trusty/universe amd64 Packages
       Hit http://archive.ubuntu.com trusty/main Translation-en
       Hit http://archive.ubuntu.com trusty/universe Translation-en
       Ign http://archive.ubuntu.com trusty/main Translation-en_US
       Ign http://archive.ubuntu.com trusty/universe Translation-en_US
       Fetched 2,442 kB in 7s (325 kB/s)
       Reading package lists...
-----> Fetching .debs for libunwind8
       Reading package lists...
       Building dependency tree...
       The following NEW packages will be installed:
         libunwind8
       0 upgraded, 1 newly installed, 0 to remove and 21 not upgraded.
       Need to get 48.3 kB of archives.
       After this operation, 194 kB of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libunwind8 amd64 1.1-2.2ubuntu3 [48.3 kB]
       Fetched 48.3 kB in 0s (160 kB/s)
       Download complete and in download only mode
-----> Fetching .debs for gettext
       Reading package lists...
       Building dependency tree...
       The following extra packages will be installed:
         gettext-base libasprintf-dev libasprintf0c2 libgettextpo-dev libgettextpo0
         libunistring0
       Suggested packages:
         gettext-doc
       The following NEW packages will be installed:
         gettext gettext-base libasprintf-dev libasprintf0c2 libgettextpo-dev
         libgettextpo0 libunistring0
       0 upgraded, 7 newly installed, 0 to remove and 21 not upgraded.
       Need to get 1,390 kB of archives.
       After this operation, 6,282 kB of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libasprintf0c2 amd64 0.18.3.1-1ubuntu3 [6,712 B]
       Get:2 http://archive.ubuntu.com/ubuntu/ trusty/main libunistring0 amd64 0.9.3-5ubuntu3 [271 kB]
       Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgettextpo0 amd64 0.18.3.1-1ubuntu3 [108 kB]
       Get:4 http://archive.ubuntu.com/ubuntu/ trusty-updates/main gettext-base amd64 0.18.3.1-1ubuntu3 [48.8 kB]
       Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main gettext amd64 0.18.3.1-1ubuntu3 [829 kB]
       Get:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libasprintf-dev amd64 0.18.3.1-1ubuntu3 [4,438 B]
       Get:7 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgettextpo-dev amd64 0.18.3.1-1ubuntu3 [122 kB]
       Fetched 1,390 kB in 1s (1,293 kB/s)
       Download complete and in download only mode
-----> Installing gettext_0.18.3.1-1ubuntu3_amd64.deb
-----> Installing gettext-base_0.18.3.1-1ubuntu3_amd64.deb
-----> Installing libasprintf0c2_0.18.3.1-1ubuntu3_amd64.deb
-----> Installing libasprintf-dev_0.18.3.1-1ubuntu3_amd64.deb
-----> Installing libgettextpo0_0.18.3.1-1ubuntu3_amd64.deb
-----> Installing libgettextpo-dev_0.18.3.1-1ubuntu3_amd64.deb
-----> Installing libunistring0_0.9.3-5ubuntu3_amd64.deb
-----> Installing libunwind8_1.1-2.2ubuntu3_amd64.deb
APT packages Installled
Installing .NET CORE 1.0.0-preview2-003121 from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-ubuntu-x64.latest.tar.gz
Found 1 project.json files
Building /tmp/tmp.DqaHrsljHp/src/znipebase/project.json
Reading App Name from project.json
znipebase
Restoring the packages

## Welcome to .NET Core!

Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

## Telemetry

The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

## Configuring...

A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 2610 ms
Expanding 100% 8152 ms
  Restoring packages for /tmp/ths4jbff.hkj/ths4jbff.hkj.csproj...
  Installing System.Xml.XPath 4.0.1.
  Installing runtime.native.System.IO.Compression 4.1.0.
  Installing Microsoft.NETCore.DotNetHost 1.0.1.
  Installing Microsoft.NETCore.Targets 1.0.1.
  Installing System.Xml.XPath.XDocument 4.0.1.
  Installing System.Xml.XmlDocument 4.0.1.
  Installing System.Text.Encoding.CodePages 4.0.1.
  Installing System.Diagnostics.StackTrace 4.0.1.
  Installing System.Diagnostics.FileVersionInfo 4.0.0.
  Installing Microsoft.CodeAnalysis.Analyzers 1.1.0.
  Installing System.Security.Cryptography.Csp 4.0.0.
  Installing System.Security.Cryptography.Cng 4.2.0.
  Installing runtime.native.System.Net.Http 4.0.1.
  Installing System.Security.Principal 4.0.1.
  Installing System.Security.Cryptography.OpenSsl 4.0.0.
  Installing System.Security.Claims 4.0.1.
  Installing runtime.native.System.Security.Cryptography 4.0.0.
  Installing runtime.native.System.Net.Security 4.0.1.
  Installing System.Security.Principal.Windows 4.0.0.
  Installing System.Reflection.Emit.Lightweight 4.0.1.
  Installing System.Threading.Overlapped 4.0.1.
  Installing System.Reflection.Emit.ILGeneration 4.0.1.
  Installing System.Reflection.Emit 4.0.1.
  Installing runtime.native.System 4.0.0.
  Installing Microsoft.Win32.Registry 4.0.0.
  Installing System.Xml.XDocument 4.0.11.
  Installing System.Xml.ReaderWriter 4.0.11.
  Installing System.Threading.Timer 4.0.1.
  Installing System.Threading.Tasks 4.0.11.
  Installing System.Text.RegularExpressions 4.1.0.
  Installing Microsoft.NETCore.App 1.0.1.
  Installing Microsoft.NET.Sdk 1.0.0-alpha-20161029-1.
  Installing System.Text.Encoding.Extensions 4.0.11.
  Installing System.Text.Encoding 4.0.11.
  Installing Libuv 1.9.0.
  Installing Microsoft.CodeAnalysis.CSharp 1.3.0.
  Installing Microsoft.CodeAnalysis.VisualBasic 1.3.0.
  Installing Microsoft.CSharp 4.0.1.
  Installing Microsoft.NETCore.DotNetHostPolicy 1.0.1.
  Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.4.
  Installing Microsoft.VisualBasic 10.0.1.
  Installing System.Runtime.Numerics 4.0.1.
  Installing NETStandard.Library 1.6.0.
  Installing System.Buffers 4.0.0.
  Installing System.Collections.Immutable 1.2.0.
  Installing System.ComponentModel 4.0.1.
  Installing System.ComponentModel.Annotations 4.1.0.
  Installing System.Diagnostics.DiagnosticSource 4.0.0.
  Installing System.Diagnostics.Process 4.1.0.
  Installing System.Dynamic.Runtime 4.0.11.
  Installing System.Globalization.Extensions 4.0.1.
  Installing System.Runtime.InteropServices.RuntimeInformation 4.0.0.
  Installing System.IO.FileSystem.Watcher 4.0.0.
  Installing System.IO.MemoryMappedFiles 4.0.0.
  Installing System.Runtime.Handles 4.0.1.
  Installing System.IO.UnmanagedMemoryStream 4.0.1.
  Installing System.Linq.Expressions 4.1.0.
  Installing System.Linq.Parallel 4.0.1.
  Installing System.Linq.Queryable 4.0.1.
  Installing System.Net.Sockets 4.1.0.
  Installing System.Net.NameResolution 4.0.0.
  Installing System.Net.Primitives 4.0.11.
  Installing System.Net.Requests 4.0.11.
  Installing System.Net.Security 4.0.0.
  Installing System.Net.WebHeaderCollection 4.0.1.
  Installing System.Numerics.Vectors 4.1.1.
  Installing System.Reflection.DispatchProxy 4.0.1.
  Installing System.Reflection.Metadata 1.3.0.
  Installing System.Reflection.TypeExtensions 4.1.0.
  Installing System.Resources.Reader 4.0.0.
  Installing System.Runtime.Loader 4.0.0.
  Installing System.Security.Cryptography.Algorithms 4.2.0.
  Installing System.Security.Cryptography.Encoding 4.0.0.
  Installing System.Security.Cryptography.Primitives 4.0.0.
  Installing System.Security.Cryptography.X509Certificates 4.1.0.
  Installing System.Threading.Tasks.Dataflow 4.6.0.
  Installing System.Threading.Tasks.Extensions 4.0.0.
  Installing System.Threading.Tasks.Parallel 4.0.1.
  Installing System.Threading.Thread 4.0.0.
  Installing System.Threading.ThreadPool 4.0.10.
  Installing NuGet.Build.Tasks.Pack 3.6.0-rc-1984.
  Installing Microsoft.NETCore.Platforms 1.0.1.
  Installing Microsoft.CodeAnalysis.Common 1.3.0.
  Installing System.Collections 4.0.11.
  Installing System.Diagnostics.Debug 4.0.11.
  Installing System.Globalization 4.0.11.
  Installing System.Linq 4.1.0.
  Installing System.ObjectModel 4.0.12.
  Installing System.Reflection 4.1.0.
  Installing System.Reflection.Extensions 4.0.1.
  Installing System.Reflection.Primitives 4.0.1.
  Installing System.Resources.ResourceManager 4.0.1.
  Installing System.Runtime 4.1.0.
  Installing System.Runtime.Extensions 4.1.0.
  Installing System.Runtime.InteropServices 4.1.0.
  Installing System.Threading 4.0.11.
  Installing Microsoft.NETCore.DotNetHostResolver 1.0.1.
  Installing Microsoft.NETCore.Jit 1.0.4.
  Installing Microsoft.NETCore.Windows.ApiSets 1.0.1.
  Installing Microsoft.Win32.Primitives 4.0.1.
  Installing System.AppContext 4.1.0.
  Installing System.Collections.Concurrent 4.0.12.
  Installing System.Console 4.0.0.
  Installing System.Diagnostics.Tools 4.0.1.
  Installing System.Diagnostics.Tracing 4.1.0.
  Installing System.Globalization.Calendars 4.0.1.
  Installing System.IO 4.1.0.
  Installing System.IO.Compression 4.1.0.
  Installing System.IO.Compression.ZipFile 4.0.1.
  Installing System.IO.FileSystem 4.0.1.
  Installing System.IO.FileSystem.Primitives 4.0.1.
  Installing System.Net.Http 4.1.0.
  Writing lock file to disk. Path: /tmp/ths4jbff.hkj/obj/project.assets.json
  Generating MSBuild file /tmp/ths4jbff.hkj/obj/ths4jbff.hkj.csproj.nuget.g.targets.
  Generating MSBuild file /tmp/ths4jbff.hkj/obj/ths4jbff.hkj.csproj.nuget.g.props.
  Restore completed in 2630.2937ms for /tmp/ths4jbff.hkj/ths4jbff.hkj.csproj.

  NuGet Config files used:
      /app/.nuget/NuGet/NuGet.Config

  Feeds used:
      /tmp/dznt5s1j.a22

  Installed:
      112 package(s) to /tmp/ths4jbff.hkj/ths4jbff.hkj.csproj
MSBUILD : error MSB1009: Project file does not exist.
Switch: /tmp/tmp.DqaHrsljHp
 !     Push rejected, failed to compile ASP.NET Core app.
 !     Push failed

**Comment by manuelz120** [comment]
@flabbert 
You are totally right that the bug is caused by a silent update of the ASP.NET Core version in the buildpack. I made a fork which prevents this issue until this repo is fixed. Feel free to use: https://github.com/manuelz120/dotnet-buildpack.

**Comment by flabbert** [comment]
Thank you, i will test it tomorrow, hopefully it fixes our issues with heroku

**Comment by manuelz120** [comment]
At least in my case it works. This is a real showstopper 😅

**Comment by flabbert** [comment]
It sure is, i had to set up an IIS server the other day to have our project hosted somewhere in the meantime.

**Comment by flabbert** [comment]
you should probably update the readme on your fork so people dont try to build with this package when reading the readme

**Comment by goenning** [comment]
@manuelz120 thanks for the fix, its working for me too! :)

**Comment by flabbert** [comment]
@manuelz120 this buildpack seems to install 1.1.0-preview version of .net core, is that intended? we are running 1.0.0 in our project and it doesnt build correctly then

**Comment by noliar** [comment]
It is a basic stupid bug of string comparison in 'compile' script.

**Comment by manuelz120** [comment]
@flabbert For me this was intended because our project is developed with this specific version and therefor I won't be affected by this silent updates again.

However, you can easily create a fork and change the Download-URL  (https://github.com/manuelz120/dotnet-buildpack/blob/master/bin/compile#L92) of the framework to the version you are using. This way you have full controlled over the environment used by heroku. 

Or you use the fix provided by noliar, so it automatically uses the version specified in your config. 👍

**Comment by goenning** [comment]
@manuelz120 Do you know to install both 1.1 and 1.0.1 binaries to run side by side? Can you share some tips? Thanks.

**Comment by manuelz120** [comment]
@goenning What do you mean by running them side by side? Do you want to start the same application twice (one time 1.1, one time 1.0.1)?

**Comment by goenning** [comment]
@manuelz120 not exactly. My app was using dotnet 1.1 while EF tools was still using dotnet 1.0 (MS didn't release a 1.1 version of this tool yet). But nevermind it, I don't need it anymore. I have just switched from EF tools to npm db-migrate.
